80 consolidate hosted osi documentation sources
OpenSimulationInterface/osi-documentation pull request #81
Opened 2024-10-22 12:53 UTC by philipwindecker

### Reference to a related issue in the repository
#80 

#### Add a description
Remove legacy links.

#### Mention a member
@TimmRuppert 

#### Check the checklist

- [x] I have performed a self-review of my own code/documentation.
- [x] My documentation changes are related to another repository in the organization. Here is the link to the issue/repo: https://github.com/OpenSimulationInterface/open-simulation-interface/issues/832
- [ ] My changes generate no new warnings during the documentation generation.

2024-10-22 14:53 UTC, TimmRuppert requested changes

2024-10-22 15:16 UTC, philipwindecker commented on README.adoc
> +This repo contains most of the AsciiDoc-based part of the documentation.
```suggestion
This repo contains most of the general AsciiDoc-based part of the documentation.
```

2024-10-22 15:17 UTC, philipwindecker commented on README.adoc
> +This repo contains most of the AsciiDoc-based part of the documentation.
I will change it.

Tip: If you use the suggestion function (file symbol with +-), your suggestion can be applied directly from you comment as new commit. :)

2024-10-22 15:20 UTC, philipwindecker commented on content/general_docs/osi_repos.adoc
> +https://github.com/OpenSimulationInterface/osi-documentation[osi-documentation]:: Source for the OSI user guide sources.
```suggestion
https://github.com/OpenSimulationInterface/osi-documentation[osi-documentation]:: Source for the AsciiDoc files used to compile the general chapters of the OSI documentation.
```

2024-10-23 07:43 UTC, TimmRuppert approved these changes

2025-07-11 08:47 UTC, merged